version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: examplepassword
    command: ["redis-server"]

  app:
    build: .
    container_name: aspnet-app
    ports:
      - "5227:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MONGO_URI: mongodb://root:example@mongo:27017
    volumes:
      - ./:/app
    depends_on:
      - mongo
      - redis
    command: ["dotnet", "watch", "run"]

volumes:
  mongo-data:
  redis-data:
