FROM node:23 AS build

WORKDIR /app

RUN npm install -g @angular/cli

COPY package*.json ./

RUN npm install --force

COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "3000", "--allowed-hosts", "frontend-angular"]