version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    image: your-backend-image
    container_name: backend-service
    networks:
      - app-network
    expose:
      - "8080"

networks:
  app-network:
    driver: bridge
